package com.quinbay.qa.training.test;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import java.util.concurrent.TimeUnit;
public class SeleniumInitial {
    public static void main(String[] args) throws InterruptedException{
        System.setProperty("webdriver.chrome.driver","src/main/resources/driver/chromedriver");
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        driver.get("https://www.edgewordstraining.co.uk/demo-site/");
        Thread.sleep(2000);
        WebElement searchbox=((ChromeDriver) driver).findElementByXPath("//input[contains(@id,'0')]");
        WebElement dismiss=((ChromeDriver) driver).findElementByXPath("//a[@class='woocommerce-store-notice__dismiss-link']");
        dismiss.click();
        searchbox.sendKeys("T Shirt");
        searchbox.submit();
        WebElement vneck=((ChromeDriver) driver).findElementByXPath("//img[@src='https://www.edgewordstraining.co.uk/demo-site/wp-content/uploads/2018/03/vneck-tee.jpg']") ;
        vneck.click();
        WebElement addtocart=((ChromeDriver) driver).findElementByXPath("//button[@value=38]");
        addtocart.click();
        WebElement viewcart=((ChromeDriver) driver).findElementByXPath("//a[@href='https://www.edgewordstraining.co.uk/demo-site/cart/'][text()='Cart']");
        viewcart.click();
        WebElement checkout=((ChromeDriver) driver).findElementByXPath("//a[@href='https://www.edgewordstraining.co.uk/demo-site/checkout/'][@class=\"checkout-button button alt wc-forward\"]");
        checkout.click();
        WebElement firstname=((ChromeDriver) driver).findElementByXPath("//input[@id=\"billing_first_name\"]");
        firstname.click();
        firstname.sendKeys("Arunraj");
        WebElement lastname=((ChromeDriver) driver).findElementByXPath("//input[@id=\"billing_last_name\"]");
        lastname.click();
        lastname.sendKeys("M");
        WebElement company=((ChromeDriver) driver).findElementByXPath("//input[@id=\"billing_company\"]");
        company.click();
        company.sendKeys("Quinbay Technologies");
        Select drpcountry=new Select(((ChromeDriver) driver).findElementByXPath("//select[@class='country_to_state country_select select2-hidden-accessible']"));
        drpcountry.selectByVisibleText("India");
        WebElement door =((ChromeDriver) driver).findElementByXPath("//input[@id='billing_address_1']");
        door.click();
        door.sendKeys("24 th mainroad,4th sector");
        WebElement city=((ChromeDriver) driver).findElementByXPath("//input[@id='billing_city']");
        city.click();
        city.sendKeys("Bangalore");
        Select state=new Select(((ChromeDriver) driver).findElementByXPath("//select[@id=\"billing_state\"]"));
        state.selectByVisibleText("Karnataka");
        WebElement postcode=((ChromeDriver) driver).findElementByXPath("//input[@id='billing_postcode']");
        postcode.click();
        postcode.sendKeys("560007");
        WebElement email=((ChromeDriver) driver).findElementByXPath("//input[@id='billing_email']");
        email.click();
        email.sendKeys("arunraj.m@quin.com");
        WebElement phone=((ChromeDriver) driver).findElementByXPath("//input[@id='billing_phone']");
        phone.click();
        phone.sendKeys("7502638295");
        WebElement createaccount=((ChromeDriver) driver).findElementByXPath("//input[@id='createaccount']");
        createaccount.click();
        WebElement pass=((ChromeDriver) driver).findElementByXPath("//input[@id='account_password']");
        pass.click();
        pass.sendKeys("gffgfgfgdgfgffgrgdfgf");
        WebElement payment=((ChromeDriver) driver).findElementByXPath("//input[@id='payment_method_cod']");
        ((JavascriptExecutor) driver).executeScript("arguments[0].checked = true;", payment);
        WebElement placeorder=((ChromeDriver) driver).findElementByXPath("//button[@id=\"place_order\"]");
        placeorder.submit();
        Thread.sleep(300000);
        driver.close();
    }
}
